sonar.projectKey=<your-github-username>_api-gateway-rl
sonar.organization=<your-sonarcloud-org-key>

sonar.sources=gateway-service/src/main/java,auth-service/src/main/java,order-service/src/main/java,product-service/src/main/java
sonar.java.binaries=gateway-service/target/classes,auth-service/target/classes,order-service/target/classes,product-service/target/classes

sonar.sourceEncoding=UTF-8
