sonar.projectKey=s11ma_api-gateway-rl
sonar.organization=s11ma

sonar.sources=gateway-service/src/main/java,auth-service/src/main/java,order-service/src/main/java,product-service/src/main/java
sonar.tests=gateway-service/src/test/java,auth-service/src/test/java,order-service/src/test/java,product-service/src/test/java
sonar.java.binaries=gateway-service/target/classes,auth-service/target/classes,order-service/target/classes,product-service/target/classes

sonar.coverage.jacoco.xmlReportPaths=gateway-service/target/site/jacoco/jacoco.xml,auth-service/target/site/jacoco/jacoco.xml,order-service/target/site/jacoco/jacoco.xml,product-service/target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
